### PR TITLE
Routes

### PR DESCRIPTION
**Pull request by valerieyang00**
Added initial components and set up routes with simple text descriptions.

### CODE REVIEW

**Review by moyara — CHANGES_REQUESTED** [review]
output usually means compiled output from source files. I'd suggest to rename and simplify the output to client/flavorite instead of output/v3.0/yaml/flavorite

Also tsconfig we only compiles src. you also need to add the client folder to import them.

**Comment by moyara** [comment]
Also could you update README and add some description of the folder structure and how to update the client model from OAS? Also please add the commands on scripts in package.json.

**Comment by valerieyang00** [comment]
For some reason, I'm not seeing 'resolve' button on this one...
But I made all changes mentioned in your comments on here +
 - Removed tailwind and installed MUI
 - created .eslintignore and added 'client' folder

* I'm not sure what you think about the readme structure, I didn't link our google doc yet in the 'About' section. Let me know if you suggest something there. Also for react scripts in available scripts, I copied from the original Readme, is this what you meant? Then I added the scripts I added for eslint, prettier, openapi.

I just closed the 'map' branch PR because I am going to re-do it with the library you recommended. Will create a new branch and open another PR when done.

**Review by moyara — APPROVED** [review]
Looks good!
I think for next task we can replace all native html elements such as `<div> <h1>` with MUI layout components such as https://mui.com/material-ui/react-box/ or typography https://mui.com/material-ui/react-typography/
Let's merge this and create a new PR for it.

**Pull request merged**
